### ISSUE TITLE
Provide suggestions for decks you've imported

### ISSUE THREAD

**Issue by Lego6245** [jceddy/DailyArenaDeckAdvisor#20]
Often times I'll see a decklist on the internet and want to give it a run. I'd love to see what suggested replacements are for it, but if it doesn't show up in the sidebar I can't see. Please provide rudimentary support for looking at a deck in your collection that's incomplete and providing suggested replacements for missing cards.

**Comment by jceddy** [comment]
I think this is a great idea.

**Comment by jceddy** [comment]
You means specifically for decks you've imported into Arena, right?

Or were you thinking of adding a deck import function to DADA?

**Comment by Lego6245** [comment]
Originally, I was thinking the first (imported into Arena). Arbitrary deck import into DADA might be nice too, but primarily I was thinking of this use case:

1) You see a netdeck or some other deck on the web and want to try it out.
2) You import it into Arena, but notice you're missing certain cards.
3) You open DADA and see the deck, what cards you're missing, and what to replace them with.

Other log parsing applications and tools have portions of this functionality (namely seeing what cards you're missing), but DADA to my knowledge is the only one that provides both a "next pack to open" guidance and suggested replacements.

**Comment by jceddy** [comment]
So what I was originally thinking was possibly to add a "pseudo-format" called "My Decks" or something that loads up your decks from Arena, and shows you the ones you are missing cards from in a similar way to how decks for other formats are currently shown...but probably either hiding your completed decks completely or just sorting them to the bottom of the list by default or something.

The only part of it that makes that implementation a little tricky is that there is now some format-specific data taken into account when generating replacement suggestions, and that implementation might make using that data properly a little tricky.

Maybe this...

When parsing the user's collection data out of the Arena real-time logs, the deck information will always be there as well, since in Arena you have to go through the deck screen to get to the collection screen, which dumps it to the log. Maybe I can add some code that runs through the user's decks and stores them away somewhere, "guessing" at the deck's format based on its configuration (i.e. if it has a sideboard, assume it's Standard, if it doesn't, assume it's Arena Standard, unless it has commander defined, in which case assume it's Brawl [we can't have brawl decks saved in our collection yet, but I've seen what they look like in the log output from looking at the Brawl planecation event output]). Then just add any incomplete decks to the list of decks for the appropriate format, generating suggestions based on the "guessed" format for the deck, and then make those bubble to the top of the tabbed list, with some different formatting.

**Comment by Lego6245** [comment]
I'd find it acceptable to skip formats not currently covered by Arena. Do
the logs not contain if a deck is marked as "Standard" or "Brawl" or
similar? I guess you don't know if a "Standard" deck is for Arena Standard
or for Bo3 Standard.

Guessing sounds like a good idea (save for Arena Standard decks that run a
sideboard for wish effects), as long as you can tweak the "guess".

**Comment by jceddy** [comment]
Decks aren't tagged in the log with any kind of format information...when choosing a deck to play in a specific format, Arena just shows you all the decks that are legal for the chosen format ("Traditional" and "Arena" Standard are interchangeable except for the fact that some cards are banned in one that aren't banned in the other currently).

Brawl decks will always have a commander defined, which I think *will* show up in the log output, but I'm not 100% sure that the way decks are dumped from the collection page is the same as the way they are dumped when you're actually going into a game (I can see commander information in a log that I use in another tool I've been messing around with when I parse logs from the Brawl event).

Anyway, even if it isn't the same, I'm sure it's fine for Brawl not to work until we actually have it. Ditto Historic...I assume I'm going to have some work to do the week after next once we see what Historic looks like in the logs files.

I think for now I'm going to plan on using the implementation I described above, guessing at the format for the deck and inserting it into the deck list for that format.

**Comment by jceddy** [comment]
Pinning this...this is the last large enhancement before the ELD release (at which time I will likely be busy hunting down rotation-related issues).

**Comment by jceddy** [comment]
This is in release 1.0.3.4, which is now available for download.
