### ISSUE TITLE
Unhandled Exception - Sending Data to Server

### ISSUE THREAD

**Issue by Entember** [jceddy/DailyArenaDeckAdvisor#229]
I don't know much about the issue it just doesn't load when I boot it up. Some progress bars will appear and load partially then text will appear saying "Unhandled Exception - Sending Data to Server". I've tried uninstalling and reinstalling, deleting the .json files, and having the collections screen open while opening it. Any help would be great. Would love to start using this application. Thanks. Here are my log files.
https://drive.google.com/file/d/1QQAUmcvD8Rm2Nt0m3Mjj7huJtRXUXSuV/view?usp=sharing

**Comment by rogerblair13** [comment]
im having the exact same thing appears it started with the new card/meta change

**Comment by viruswarn** [comment]
You can fid my logs here: https://we.tl/t-0Zq4BWsZHr

Same issue here since the last MTGA release few days ago. For the record, in order to avoid the infamous black screen I had to run multiple instance of the game.

Also if I check my browser setting with https://www.localeplanet.com/support/browser.html, I got 
navigator.browserLanguage: undefined
navigator.language: fr-FR

request.getLocale(): fr_FR.
request.getLocales(): fr_FR, fr, en_US, en.

I have also deleted all the json-files but the issue remains.

I have checked the log, here is what I've found:

{"@t":"2020-09-20T06:40:40.7329280Z","@mt":"Exception in {0} ({1} - {2})","@l":"Error","@x":"System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.\r\n   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)\r\n   at System.Double.Parse(String s, IFormatProvider provider)\r\n   at DailyArena.DeckAdvisor.MainWindow.ReloadAndCrunchAllData()\r\n   at System.Threading.Tasks.Task.Execute()\r\n   --- End of inner exception stack trace ---\r\n---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.\r\n   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)\r\n   at System.Double.Parse(String s, IFormatProvider provider)\r\n   at DailyArena.DeckAdvisor.MainWindow.ReloadAndCrunchAllData()\r\n   at System.Threading.Tasks.Task.Execute()<---\r\n","0":"loadTask","1":"Window_Loaded","2":"Main Application"}


Last but not least, few months ago, on the launch day we already got a black screen like few days ago. One of the workaround was about changing the game langage setting (from XX to English)...I guess WOTC did a mess again about this point.

Hope it can help.

**Comment by Echtze1t** [comment]
Just came here to say that I have the same error. I'm in dire need of this app :) Hopefully someone can find a fix soon!

**Comment by jceddy** [comment]
Sorry it took me so long to get over here. I am getting the same error and will be looking into it tomorrow.

**Comment by jceddy** [comment]
It looks like they changed the version string so it is not a double anymore, which is causing an exception. Should have a fix pretty quickly.

**Comment by jceddy** [comment]
I fixed the ClientVersion issue, but there are some other issues beyond that one that I am looking into now.

**Comment by jceddy** [comment]
Version 1.0.8.7 is now available, and should fix these issues.

**Comment by viruswarn** [comment]
It works fine for me now, thank you very much Joseph!
