### ISSUE TITLE
Empty meta-report for rotation-proof option

### ISSUE THREAD

**Issue by Guikdr** [jceddy/DailyArenaDeckAdvisor#258]
Hi there,

Since the new version has been released, my meta report page is empty for rotation proof simulation.
https://ibb.co/hKngd6k

It still works fine in the "rotation agnostic" case.
https://ibb.co/0CdQr4t

I tried deleting the .json files then relaunch the app, with no success.

Thank you very much for your help (and work).

Best,

**Comment by jceddy** [comment]
Looks like it must be considering some cards as "rotating" for some reason...these screens should be exactly the same since rotation doesn't happen until September.

Will look into it.

There were some changes I think in the latest version due to cards not being treated as legal that should be, my guess is that those changes didn't make it to the "Rotation Proof" code path. I will check it when I have a chance.

Thanks for bringing it to my attention...will be good to fix before the next rotation comes. 😅

**Comment by Guikdr** [comment]
Thank you for looking into it :)

Just one thing : are you sure both screens should be the same...? Rotation-proof page should only include cards from Zendikar and later extensions, while rotation-agnostic page can also include all cards from soon-rotating extensions (Ikoria, Theros, Eldraine...), am I right ?

**Comment by jceddy** [comment]
You're right, and you know what, the reason this isn't showing anything right now is that there are no rotation-proof decks in the system for it to show yet. I tested it today by creating a rotation-proof deck with missing cards in my collection and verifying that it shows up with the rotation toggle in either position.

Also, it's still using the "official" definition of standard, so won't treat AFR cards as standard legal until this weekend.

I'm going to close this issue for now since it's actually working as expected ATM, just with a bit of a delay.

I am looking into changing over to a different source for decklists and standard info, and hopefully will be able to add more formats to the tool at the same time.
