### ISSUE TITLE
v1.0.3.5 Arena Standard has no content listed

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#28]
Switching to Brawl or Standard displays contents as expected.

Arena Standard is empty
![Screenshot_092819_081205_PM](https://user-images.githubusercontent.com/13244707/65823863-41175f80-e22c-11e9-80e1-0dbeacd8c55f.jpg)

**Comment by ghost** [comment]
![Screenshot_092819_081252_PM](https://user-images.githubusercontent.com/13244707/65823871-60ae8800-e22c-11e9-8868-ee8e2b43d17b.jpg)

**Comment by jceddy** [comment]
D'oh. They were there yesterday, right?

Will check this when I can.

**Comment by ghost** [comment]
yes  - it seemed to start after I got some more cards and some card styles

**Comment by ghost** [comment]
A little more info - I just uninstalled and reinstalled and now it gets
stuck at 'Loading deck archetypes...'

I did win a few more games and get more ELD packs - not sure if that has
anything to do with it.

Mark

**Comment by ghost** [comment]
I fixed it by deleting all my json files and restarting - sorry for the
fire drill

**Comment by ghost** [comment]
nope nope - as soon as I go back to Arena Standard it hangs at loading deck
archetypes. the file arena_standard_decks.json gets created and then the
app stops

**Comment by jceddy** [comment]
Last night I fixed a server side bug that was causing Arena Standard decks not to get picked up properly.  
  
Ran into the bug you're now seeing (hanging on the load page), but haven't had a chance to figure that one out yet.

**Comment by jceddy** [comment]
Turns out this was due to mtgarena.pro handling Adventure "split" cards in a nonstandard way. I added code to detect it and handle it (in such a way that it shouldn't break if they change those names back to match Arena), and pushed release 1.0.3.6 with the fix.

I'm going to close the issue, but if someone else on here could verify and re-open if it's still broken for them, that would be cool.
