### ISSUE TITLE
v1.0.3.6 not displaying meta report for Arena Standard

### ISSUE THREAD

**Issue by ghost** [jceddy/DailyArenaDeckAdvisor#29]
![Screenshot_100419_083240_AM](https://user-images.githubusercontent.com/13244707/66207897-f1002900-e681-11e9-9ea6-559ce91f4592.jpg)
[dada.zip](https://github.com/jceddy/DailyArenaDeckAdvisor/files/3690538/dada.zip)

Screen shot and log files added. Works OK for Standard, but once Arena selected - boom.

I did clean slate as well.

**Comment by jceddy** [comment]
Should be fixed now. This is rotation-related...it was set up to pull decks that were active since the last set release...which in this case was today.

I added a one-week "fudge factor" to get decks pulled in.

There are slim pickings currently for "new standard" decks, but they should start filling out as we progress into it.
