### ISSUE TITLE
suggested replacement - godless shrine (B/W) with Sacred Foundry (R/W)

### ISSUE THREAD

**Issue by justshawnf** [jceddy/DailyArenaDeckAdvisor#3]
![image](https://user-images.githubusercontent.com/54459982/63630476-1ca2e480-c5e9-11e9-8093-9e050d92c818.png)

**Comment by jceddy** [comment]
Turns out this is because if a land replacement isn't found on the first pass (one that matches the missing lands colors exactly), it is relaxing the restrictions too much and just basically picking a land based solely on the fixed rank.

I'll make a change to handle this better...for now it will just fall back to basic lands if it can't find a replacement on the first pass. In this specific case, it should suggest 1x Plains and 1x Swamp as the replacement for 2x Godless Shrine.

**Comment by jceddy** [comment]
@justshawnf  - Can I get a copy of your log from from C:\Users\\{Your User}\AppData\LocalLow\Wizards of the Coast\MTGA (your drive letter may be different) to test this with?

I think I have a fix, but would like to test it against your player inventory to verify.
