### ISSUE TITLE
Not able to pull card database

### ISSUE THREAD

**Issue by Oredna** [jceddy/DailyArenaDeckAdvisor#5]
I resently have problem pulling the card database. I had similar problem with mtg pro tracker but on it when i press manual re-sync it ok. Maybe have the same button, and not only the loading screen ? can i help by providing some logs or ?

**Comment by jceddy** [comment]
If you can provide the latest logs from the logs folder, it could be helpful.

There was an issue earlier today with some of the data coming from scryfall...I've since fixed it and added some code to keep it from causing a failure again to the program, as well. I'm not sure whether you're seeing the same issue, but if so, deleting the information in the AppData folder and re-running the program might fix it.

**Comment by Oredna** [comment]
it ok now, i dont know what fix it. i am closing the isue
