### ISSUE TITLE
Suggest upgrades

### ISSUE THREAD

**Issue by frankcalise** [jceddy/DailyArenaDeckAdvisor#69]
Is it possible to use your algorithm in reverse?

For example, if there is a deck I have in the app you provide replacements for cards I don't have, which is helpful.

What if I try to craft my own deck and my collection isn't the best, the deck could use some upgrades. Could the app suggest which of my cards are weaker and provide suggestions on better ones?

**Comment by jceddy** [comment]
Deciding which cards are "weaker" is a bit beyond the scope of the tool, since often deck builders will understand something about card interactions that the tool won't. If you suspect that some cards are weak, you could always remove them from the deck and see what the tool suggests when they are gone. Maybe this could be made easier to do within the tool by allowing you to remove cards from a player deck in the tool itself without requiring that you go mess with it in Arena and re-dump the data to the Arena log?  
  
Or are you maybe thinking about having the tool make suggestions of card to craft to replace bad/mediocre cards from your collection that you used while deck building? If so, that's kind of beyond the scope of this tool, too, as it relies on deck data from external sources when suggesting decks/replacements/etc. The best it would really be able to do in this case is suggest the top deck from its deck database.

So I'm trying to think of what useful functionality could be added along these lines that wouldn't go way outside the lines of what DADA is meant to be used for...maybe this:

* Add a filter to show all player decks (turn it on and "complete" decks are also included in the "Player Decks" section of the deck tab list)
* Add a "Suggest Upgrades" button to the deck details page for player decks (maybe only shown for "complete decks"? Maybe not). When you click that button, it executes some algorithm to find the "closest" deck to that player deck from its database, with ties being broken by the default sort value, then gives you a link to that deck.

What do you think? Not sure if any of this gets it to the functionality you're looking for.

**Comment by frankcalise** [comment]
I understand your second point that the crafter would understand the intricacies of the cards interacting with each other. The local editing you first mentioned without editing in Arena and then it log dumping first could be cool.

Toggle certain cards to "remove" them and see what the replacement list comes up with.

Your final bullet is also cool, helps find a meta deck similar to one you were trying to build. It's kind of difficult to search decks around some base cards you would like to include.

Just thoughts, I'm new to the game. I code though, so if I can jump in and help in anyway I'll make the effort if you do find a feature set you think is on par with what you're aiming for with the tool.

Thanks for the replies!

**Comment by frankcalise** [comment]
Or maybe from the Top Cards to Collect/Craft, could click them and help filter the deck list down. So you could build around specific cards, but find the decks that include them.

**Comment by jceddy** [comment]
Actually, I think a filter that filters decks by card text information would be really good to have...I've been thinking about adding it since there were a couple of times that I wanted it, but didn't get around to it yet.

I think we probably have two or three good enhancement candidates here:
1) Ability to "ignore" cards from decks (or your collection) to get replacement suggestions for them even if you actually own them already.
2) Text-based card filter. I actually have the rules text in the database, so could include this in that filter.

**Comment by frankcalise** [comment]
Those ideas sound good, I think they'd be good additions.

**Comment by jceddy** [comment]
Created new issues #71 and #72. Closing this one.
