### ISSUE TITLE
filter decks with low number of matches, or lower than % winrate

### ISSUE THREAD

**Issue by ersatyle** [jceddy/DailyArenaDeckAdvisor#79]
I'm sorting decks by win / loss record, but some of them have a very low number of matches played ( like 4 matches play, win / loss 4/1) 
It would be nice to show only deck with at least XX total game played

Aditionally it would be nice to have the ability to filter out deck with a low winrate ratio

![image](https://user-images.githubusercontent.com/21692877/68781751-3c551200-0606-11ea-87eb-58007085e9b6.png)

**Comment by jceddy** [comment]
This is a great suggestion. I've found myself having the same issue and basically having to "skip" the first few decks in the list after sorting.

On a related note I might add some kind of other win/loss math similar to MMR or ELO that takes number of games into account when calculating a score.

**Comment by jceddy** [comment]
This feature seems overwhelmingly popular...got 75+% of the vote when I polled which feature to work on next, so I will try to work on this one this week as I am able.

My current plan is to introduce some kind of MMR/ELO-style score to use in the default sort for Arena Standard decks, and also to add filtering on Win Rate, Games Recorded, and the new score.

**Comment by jceddy** [comment]
After messing around with this, what I've decided to do is assign a score that is equivalent to the bottom end of the 99% confidence interval based on the win/loss sample.

This basically means the score is pessimistic about how good a deck is until it has a lot of data to back up the win rate estimate.

Here is some example data, sorted by win rate:

Name | Wins | Losses | Total Games | Win Percentage | Score
-- | -- | -- | -- | -- | --
Deck A | 2 | 1 | 3 | 66.67 | 26.13
Deck B | 13 | 7 | 20 | 65 | 58.85
Deck C | 893 | 603 | 1496 | 59.69 | 59.61
Deck D | 1717 | 1162 | 2879 | 59.64 | 59.59
Deck E | 341 | 233 | 574 | 59.41 | 59.19
Deck F | 3445 | 2361 | 5806 | 59.34 | 59.31
Deck G | 952 | 656 | 1608 | 59.2 | 59.13
Deck H | 442 | 315 | 757 | 58.39 | 58.22
Deck I | 2288 | 1687 | 3975 | 57.56 | 57.53
Deck J | 347 | 257 | 604 | 57.45 | 57.24
Deck K | 79 | 59 | 138 | 57.25 | 56.32
Deck L | 5633 | 5049 | 10682 | 52.73 | 52.72
Deck M | 7757 | 7217 | 14974 | 51.8 | 51.79
Deck N | 952 | 1132 | 2084 | 45.68 | 45.62

Here you can see that even though Deck A has the highest recorded win rate, it actually has the lowest score. Since we only have 3 games recorded, the score basically assumes the wins were luck until we get more data to show otherwise.

Here's the same data set, sorted by the score based on the bottom of the confidence interval:

Name | Wins | Losses | Total Games | Win Percentage | Score
-- | -- | -- | -- | -- | --
Deck C | 893 | 603 | 1496 | 59.69 | 59.61
Deck D | 1717 | 1162 | 2879 | 59.64 | 59.59
Deck F | 3445 | 2361 | 5806 | 59.34 | 59.31
Deck E | 341 | 233 | 574 | 59.41 | 59.19
Deck G | 952 | 656 | 1608 | 59.2 | 59.13
Deck B | 13 | 7 | 20 | 65 | 58.85
Deck H | 442 | 315 | 757 | 58.39 | 58.22
Deck I | 2288 | 1687 | 3975 | 57.56 | 57.53
Deck J | 347 | 257 | 604 | 57.45 | 57.24
Deck K | 79 | 59 | 138 | 57.25 | 56.32
Deck L | 5633 | 5049 | 10682 | 52.73 | 52.72
Deck M | 7757 | 7217 | 14974 | 51.8 | 51.79
Deck N | 952 | 1132 | 2084 | 45.68 | 45.62
Deck A | 2 | 1 | 3 | 66.67 | 26.13

As you can see, Deck A got sorted to the bottom of the list, since we are not confident in the reported win rate, at all, while deck B got pushed way down (it also had a small number of games reported). Most of the rest of the decks are in roughly the same order, but other decks with < 1000 sample games got dinged. Once you're over 1000 games played, the confidence score gets pretty close to the reported win rate, while over 10000 games makes them almost identical (off by only .01).

**Comment by jceddy** [comment]
By the way, the calculation being used for the score is:

Variance = Winrate*(1-WinRate)/TotalGames
Deviation = SQRT(Variance)
BaseScore = WinRate-2.58*(Deviation/SQRT(TotalGames))
Score = 100*BaseScore

**Comment by jceddy** [comment]
I ended up not adding a "Win Rate" filter, since it's redundant to have both a "Deck Score" and "Win Rate" filter.

Checked in these changes in commit d7a9614, it will be included in the next release.

**Comment by jceddy** [comment]
Pushed version 1.0.6.3, which contains these changes.
Closing.
